-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Sep 26, 2020 at 05:54 PM
-- Server version: 5.7.26
-- PHP Version: 7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `stylecreek`
--

-- --------------------------------------------------------

--
-- Table structure for table `beds`
--

DROP TABLE IF EXISTS `beds`;
CREATE TABLE IF NOT EXISTS `beds` (
  `id` int(50) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `price` int(50) NOT NULL,
  `discount_price` int(50) NOT NULL,
  `discount_percent` int(50) NOT NULL,
  `buy_count` int(50) NOT NULL,
  `highlights` text NOT NULL,
  `info` text NOT NULL,
  `img` varchar(50) NOT NULL,
  `img1` varchar(50) NOT NULL,
  `img2` varchar(50) NOT NULL,
  `img3` varchar(50) NOT NULL,
  `review_name` varchar(50) NOT NULL,
  `review` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `beds`
--

INSERT INTO `beds` (`id`, `name`, `price`, `discount_price`, `discount_percent`, `buy_count`, `highlights`, `info`, `img`, `img1`, `img2`, `img3`, `review_name`, `review`) VALUES
(1, 'Symphony Engineered Wood Queen Box Bed', 21549, 15390, 28, 25, '<br>-Bed Material Subtype: Particle Board\r\n<br>-W x H x D: 158.1 cm x 88.1 cm x 216.5 cm (5 ft 2 in x 2 ft 10 in x 7 ft 1 in)\r\n<br>-Storage Type: Box\r\n<br>-Recommended Mattress Size: 78x60 inches\r\n<br>-Delivery Condition: Knock Down  \r\n<br>-Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Bed\r\n<br>Model Number\r\nTQB1\r\n<br>Model Series Name\r\nSymphony\r\n<br>Bed Size\r\nQueen\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBrown\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nYes\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nEngineered Wood\r\n<br>Bed Material Subtype\r\nParticle Board\r\n<br>Headboard Material\r\nEngineered Wood\r\n<br>Headboard Material Subtype\r\nParticle Board\r\n<br>Upholstery Included\r\nNo\r\n<br>Finish Type\r\nMelamine\r\n<br>Finish Color\r\nDark Wenge\r\n<br>Storage Type\r\nBox\r\n<br>Headboard Type\r\nOpen Storage\r\n<br>Other Details\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\n<br>Do Not Move or Push Without Dismantling, Do Not Use Acid to Clean, Do Not Abuse Closing by Legs, Use Dry Cloth to Wipe Furniture, Do Not Lift the Furniture by Holding Top, Do Not Put Water on it\r\n<br>Low Profile\r\nNo\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n158.1 cm\r\n<br>Height\r\n88.1 cm\r\n<br>Depth\r\n216.5 cm\r\n<br>Floor Clearance\r\n0 cm\r\n<br>Weight\r\n115 kg\r\n<br>Recommended Mattress Size\r\n78x60 inches', 'beds/beds_a0.jpeg', 'beds/beds_a1.jpeg', 'beds/beds_a2.jpeg', 'beds/beds_a3.jpeg', '', ''),
(2, 'Forzza Jasper Engineered Wood Queen Bed', 32100, 11999, 62, 20, '<br>-Bed Material Subtype: Particle Board\r\n<br>-W x H x D: 156 cm x 90 cm x 211 cm (5 ft 1 in x 2 ft 11 in x 6 ft 11 in)\r\n<br>-Recommended Mattress Size: Length : 78 inches , Breadth : 60 inches\r\n<br>-Delivery Condition: Knock Down \r\n<br>-Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Queen Size Bed\r\n<br>Model Number\r\nFO-JasQ_We\r\n<br>Model Series Name\r\nJasper\r\n<br>Bed Size\r\nQueen\r\n<br>Bed Type\r\nPlatform\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBlack\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nNo\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nEngineered Wood\r\n<br>Bed Material Subtype\r\nParticle Board\r\n<br>Headboard Material\r\nEngineered Wood\r\n<br>Headboard Material Subtype\r\nParticle Board\r\n<br>Upholstery Included\r\nNo\r\n<br>Upholstery Color\r\nWenge\r\n<br>Finish Type\r\nLaminate\r\n<br>Finish Color\r\nWenge\r\n<br>Headboard Type\r\nOpen Storage\r\n<br>Other Details\r\n<br>Style\r\nContemporary & Modern\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\nDo your best to position your bed in such a way that there is a solid wall behind the headboard.A strong supporting wall behind your bed is desirable as per feng shui. This creates strong, protective energy around your bed, gives it more power and ability to create and hold good energy.Handle with care.Vacuum cleaning is recommended.Avoid using sharp objects.\r\n<br>Low Profile\r\nYes\r\n<br>Headboard Included\r\nYes\r\n<br>Origin of Manufacture\r\nIndia\r\n<br>Dimensions\r\n<br>Width\r\n156 cm\r\n<br>Height\r\n90 cm\r\n<br>Depth\r\n211 cm\r\n<br>Floor Clearance\r\n2 cm\r\n<br>Weight\r\n81 kg\r\n<br>Recommended Mattress Size\r\nLength : 78 inches , Breadth : 60 inches', 'beds/beds_b0.jpeg', 'beds/beds_b1.jpeg', 'beds/beds_b2.jpeg', 'beds/beds_b3.jpeg', '', ''),
(3, 'Opus Engineered Wood Queen Box Bed', 15299, 11990, 21, 17, '<br>-Bed Material Subtype: Particle Board\r\n<br>-W x H x D: 162.05 cm x 79.75 cm x 213.1 cm (5 ft 3 in x 2 ft 7 in x 6 ft 11 in)\r\n<br>-Storage Type: Box\r\n<br>-Delivery Condition: Knock Down  \r\n<br>-Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Bed\r\n<br>Model Number\r\nBQWAL00HHBS101P\r\n<br>Model Series Name\r\nOpus\r\n<br>Bed Size\r\nQueen\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBrown\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nYes\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nEngineered Wood\r\n<br>Bed Material Subtype\r\nParticle Board\r\n<br>Upholstery Included\r\nNo\r\n<br>Upholstery Color\r\nBrown\r\n<br>Finish Type\r\nLaminate\r\n<br>Finish Color\r\nMelamine Walnut\r\n<br>Storage Type\r\nBox\r\n<br>Headboard Type\r\nOpen Storage\r\n<br>Other Details\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\nDo Not Move or Push without Dismantling, Do not Use Acid to Clean, Do Not Abuse Closing by Legs, Use Dry Cloth to Wipe Furniture. Do Not Lift the Furniture by Holding Top, Do Not Put Water on It\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n162.05 cm\r\n<br>Height\r\n79.75 cm\r\n<br>Depth\r\n213.1 cm\r\n<br>Floor Clearance\r\n0 cm\r\n<br>Weight\r\n109 kg', 'beds/beds_c0.jpeg', 'beds/beds_c1.jpeg', 'beds/beds_c2.jpeg', 'beds/beds_c3.jpeg', '', ''),
(4, 'Evok Parth Engineered Wood King Box Bed', 32750, 17090, 47, 20, '<br>-Bed Material Subtype: Particle Board\r\n<br>-W x H x D: 186.6 cm x 90 cm x 208.9 cm (6 ft 1 in x 2 ft 11 in x 6 ft 10 in)\r\n<br>-Storage Type: Box\r\n<br>-Delivery Condition: Knock Down \r\n<br>-Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Bed\r\n<br>Model Number\r\nFBIBKBPBMTWN11480M\r\n<br>Model Series Name\r\nParth\r\n<br>Bed Size\r\nKing\r\n<br>Bed Type\r\nPlatform\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBrown\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nYes\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nEngineered Wood\r\n<br>Bed Material Subtype\r\nParticle Board\r\n<br>Headboard Material\r\nEngineered Wood\r\n<br>Headboard Material Subtype\r\nParticle Board\r\n<br>Upholstery Included\r\nNo\r\n<br>Finish Type\r\nLaminate\r\n<br>Finish Color\r\nWalnut\r\n<br>Storage Type\r\nBox\r\n<br>Headboard Type\r\nBasic\r\n<br>Other Details\r\n<br>Care Instructions\r\nClean With Soft Clowth : Do not use water\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n186.6 cm\r\n<br>Height\r\n90 cm\r\n<br>Depth\r\n208.9 cm\r\n<br>Floor Clearance\r\n2.5 cm\r\n<br>Weight\r\n149 kg', 'beds/beds_d0.jpeg', 'beds/beds_d1.jpeg', 'beds/beds_d2.jpeg', 'beds/beds_d3.jpeg', '', ''),
(5, 'Perfect Homes PureWood Sheesham Queen Bed', 51434, 29890, 41, 34, '<br>-Bed Material Subtype: Rosewood (Sheesham)\r\n<br>-W x H x D: 163 cm x 111 cm x 208 cm (5 ft 4 in x 3 ft 7 in x 6 ft 9 in)\r\n<br>-Storage Type: Box\r\n<br>-Recommended Mattress Size: Length = 78 inches x Width = 60 inches\r\n<br>-Delivery Condition: Knock Down - Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Bed pure sheehsam wood\r\n<br>Model Number\r\nBQWL05NHBS0401D1P\r\n<br>Model Series Name\r\nSheesham Wood\r\n<br>Bed Size\r\nQueen\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBrown\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nYes\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nSolid Wood\r\n<br>Bed Material Subtype\r\nRosewood (Sheesham)\r\n<br>Headboard Material\r\nSolid Wood\r\n<br>Headboard Material Subtype\r\nRosewood (Sheesham)\r\n<br>Upholstery Included\r\nNo\r\n<br>Finish Type\r\nPolish\r\n<br>Finish Color\r\nWalnut\r\n<br>Storage Type\r\nBox\r\n<br>Headboard Type\r\nBasic\r\n<br>Other Details\r\n<br>Style\r\nVintage & Imperial\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\nIt is always advisable to keep your furniture away from direct sunlight and places with high humidity levels. Always use coasters or mats to keep any hot object on the wooden furniture as it may get damaged by causing white rings or marks. Don\'t use any strong agents to clean the furniture unless mentioned otherwise. Keep pointed and sharp objects away from your furniture as they can cause permanent scratched.\r\n<br>Low Profile\r\nNo\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n163 cm\r\n<br>Height\r\n111 cm\r\n<br>Depth\r\n208 cm\r\n<br>Floor Clearance\r\n25 mm\r\n<br>Weight\r\n49 kg\r\n<br>Recommended Mattress Size\r\nLength = 78 inches x Width = 60 inches\r\n', 'beds/beds_e0.jpeg', 'beds/beds_e1.jpeg', 'beds/beds_e2.jpeg', 'beds/beds_e3.jpeg', '', ''),
(6, 'Barewether Maple Engineered Wood Queen Box Bed', 19499, 12990, 33, 13, '<br>-Bed Material Subtype: Particle Board\r\n<br>-W x H x D: 160.78 cm x 80.51 cm x 211.83 cm (5 ft 3 in x 2 ft 7 in x 6 ft 11 in)\r\n<br>-Storage Type: Box\r\n<br>-Delivery Condition: Knock Down - Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Queen Bed\r\n<br>Model Number\r\nZA0011WE\r\n<br>Model Series Name\r\nMaple\r\n<br>Bed Size\r\nQueen\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBlack\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nYes\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nEngineered Wood\r\n<br>Bed Material Subtype\r\nParticle Board\r\n<br>Headboard Material\r\nEngineered Wood\r\n<br>Headboard Material Subtype\r\nParticle Board\r\n<br>Upholstery Included\r\nNo\r\n<br>Finish Type\r\nMelamine\r\n<br>Finish Color\r\nWenge\r\n<br>Storage Type\r\nBox\r\n<br>Headboard Type\r\nBasic\r\n<br>Other Details\r\n<br>Style\r\nContemporary & Modern\r\n<br>Care Instructions\r\nDo Not Move or Push Without Dismantling. It is Recommended to Wipe the Furniture with a Clean Damp Cloth. Do Not Use Detergents or Strong Cleaning Agents. Use Coasters or Mats When Placing Anything Hot, Cold or Wet on Surfaces. Wipe Any Spills and Stains Immediately with a Clean Dry Cloth. Do Not Allow Water to Accumulate on or Near the furniture. Avoid Prolonged Exposure to Sunlight, as It may Cause the Color of Engineered Wood to Fade\r\n<br>Low Profile\r\nNo\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n160.78 cm\r\n<br>Height\r\n80.51 cm\r\n<br>Depth\r\n211.83 cm\r\n<br>Floor Clearance\r\n0 cm\r\n<br>Weight\r\n105 kg', 'beds/beds_f0.jpeg', 'beds/beds_f1.jpeg', 'beds/beds_f2.jpeg', 'beds/beds_f3.jpeg', '', ''),
(7, 'Home Edge Sheesham Wood King Drawer Bed', 45499, 33590, 26, 21, '<br>-Bed Material Subtype: Rosewood (Sheesham)\r\n<br>-W x H x D: 198 cm x 109 cm x 183 cm (6 ft 5 in x 3 ft 6 in x 6 ft)\r\n<br>-Storage Type: Drawer\r\n<br>-Recommended Mattress Size: 182.88 x 198.12 cm\r\n<br>-Delivery Condition: DIY - Basic assembly to be done with simple tools by the customer, comes with instructions.', '<br>General\r\n<br>Sales Package\r\n1 Bed\r\n<br>Model Number\r\nWeavekingstorage_1\r\n<br>Model Series Name\r\nSheesham Wood\r\n<br>Bed Size\r\nKing\r\n<br>Delivery Condition\r\nDIY(Do-It-Yourself)\r\n<br>Primary Color\r\nBrown\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nYes\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nSolid Wood\r\n<br>Bed Material Subtype\r\nRosewood (Sheesham)\r\n<br>Headboard Material\r\nSolid Wood\r\n<br>Headboard Material Subtype\r\nRosewood (Sheesham)\r\n<br>Upholstery Included\r\nNo\r\n<br>Finish Type\r\nPolish\r\n<br>Finish Color\r\nTeak\r\n<br>Storage Type\r\nDrawer\r\n<br>Headboard Type\r\nBasic\r\n<br>Other Details\r\n<br>Style\r\nContemporary & Modern\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\nWipe with Soft Fabric\r\n<br>Low Profile\r\nNo\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n198 cm\r\n<br>Height\r\n109 cm\r\n<br>Depth\r\n183 cm\r\n<br>Floor Clearance\r\n50.8 cm\r\n<br>Weight\r\n130 kg\r\n<br>Recommended Mattress Size\r\n182.88 x 198.12 cm', 'beds/beds_g0.jpeg', 'beds/beds_g1.jpeg', 'beds/beds_g2.jpeg', 'beds/beds_g3.jpeg', '', ''),
(8, 'Forzza Nicolas Engineered Wood Queen Bed', 39000, 17999, 53, 26, '<br>-Bed Material Subtype: Particle Board\r\n<br>-W x H x D: 159 cm x 110 cm x 205.8 cm (5 ft 2 in x 3 ft 7 in x 6 ft 9 in)\r\n<br>-Recommended Mattress Size: Length : 78 inches , Breadth : 60 inches\r\n<br>-Delivery Condition: Knock Down - Delivered in non-assembled pieces, installation by service partner', '<br>General\r\n<br>Sales Package\r\n1 Queen Bed\r\n<br>Model Number\r\nFO-UPQUN02\r\n<br>Model Series Name\r\nNicolas\r\n<br>Bed Size\r\nQueen\r\n<br>Bed Type\r\nPlatform\r\n<br>Delivery Condition\r\nKnock Down\r\n<br>Primary Color\r\nBlack\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nNo\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nEngineered Wood\r\n<br>Bed Material Subtype\r\nParticle Board\r\n<br>Headboard Material\r\nLeatherette\r\n<br>Headboard Material Subtype\r\nPU Leatherette\r\n<br>Upholstery Included\r\nYes\r\n<br>Upholstery Type\r\nTufted\r\n<br>Upholstery Color\r\nBlack\r\n<br>Finish Type\r\nMelamine\r\n<br>Finish Color\r\nBlack\r\n<br>Headboard Type\r\nUpholstered\r\n<br>Other Details\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\nDo your best to position your bed in such a way that there is a solid wall behind the headboard.A strong supporting wall behind your bed is desirable as per feng shui. This creates strong, protective energy around your bed, gives it more power and ability to create and hold good energy.Handle with care.Vacuum cleaning is recommended.Avoid using sharp objects.\r\n<br>Low Profile\r\nYes\r\n<br>Headboard Included\r\nYes\r\n<br>Dimensions\r\n<br>Width\r\n159 cm\r\n<br>Height\r\n110 cm\r\n<br>Depth\r\n205.8 cm\r\n<br>Floor Clearance\r\n30 cm\r\n<br>Weight\r\n98 kg\r\n<br>Recommended Mattress Size\r\nLength : 78 inches , Breadth : 60 inches\r\n', 'beds/beds_h0.jpeg', 'beds/beds_h1.jpeg', 'beds/beds_h2.jpeg', 'beds/beds_h3.jpeg', '', ''),
(9, 'Perfect Homes Sheesham Wood Solid Wood Single Bed', 15863, 10799, 31, 15, '<br>-Bed Material Subtype: Rosewood (Sheesham)\r\n<br>-W x H x D: 185 cm x 16 cm x 94 cm (6 ft x 6 in x 3 ft 1 in)\r\n<br>-Recommended Mattress Size: 72 x 36 inches\r\n<br>-Delivery Condition: Pre Assembled (Ready to Use)', '<br>General\r\n<br>Sales Package\r\n1 Trundle Bed\r\n<br>Model Number\r\nBSHS5NHBS0500\r\n<br>Model Series Name\r\nSheesham Wood\r\n<br>Bed Size\r\nSingle\r\n<br>Delivery Condition\r\nPre-assembled\r\n<br>Primary Color\r\nBrown\r\n<br>Suitable For\r\nBedroom\r\n<br>Storage Included\r\nNo\r\n<br>With Mattress\r\nNo\r\n<br>Body And Design Details\r\n<br>Bed Material\r\nSolid Wood\r\n<br>Bed Material Subtype\r\nRosewood (Sheesham)\r\n<br>Headboard Material\r\nSolid Wood\r\n<br>Headboard Material Subtype\r\nRosewood (Sheesham)\r\n<br>Upholstery Included\r\nNo\r\n<br>Finish Type\r\nPolish\r\n<br>Finish Color\r\nDark Brown\r\n<br>Mattress Type\r\nSingle Size\r\n<br>Headboard Type\r\nBasic\r\n<br>Other Details\r\n<br>Style\r\nContemporary & Modern\r\n<br>Platform\r\nNo\r\n<br>Care Instructions\r\nHandle with care\r\n<br>Low Profile\r\nYes\r\n<br>Headboard Included\r\nNo\r\n<br>Dimensions\r\n<br>Width\r\n185 cm\r\n<br>Height\r\n16 cm\r\n<br>Depth\r\n94 cm\r\n<br>Floor Clearance\r\n26 cm\r\n<br>Weight\r\n30 kg\r\n<br>Recommended Mattress Size\r\n72 x 36 inches', 'beds/beds_i0.jpeg', 'beds/beds_i1.jpeg', 'beds/beds_i2.jpeg', 'beds/beds_i3.jpeg', '', '');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
